language: python
cache: pip
python:
  - "3.6"
dist: trusty
env:
  global:
  - PIP_USE_MIRRORS=true
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database travisci;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=gnosisdb manage.py test --settings=config.settings.test
deploy:
  - provider: script
    script: bash scripts/deploy_docker.sh staging
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy_docker.sh develop
    on:
      branch: develop
  - provider:
    script: bash scripts/deploy_docker.sh $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
after_success:
  - coveralls
