version: '3'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.13-alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-shared:/nginx
    depends_on:
      - web

  ipfs:
    hostname: ipfs
    build:
      context: .
      dockerfile: docker/ipfs/Dockerfile
    ports:
      - "4001:4001"
      - "5001:5001"

  rabbit:
    image: rabbitmq:3-alpine
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=gnosisdb
      - RABBITMQ_DEFAULT_PASS=gnosisdb
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"

  web:
    command: docker/web/run_web.sh
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    links:
      - db
      - ipfs
    depends_on:
      - ipfs
      - db
    volumes:
      - nginx-shared:/nginx

  worker: &worker
    command: docker/web/celery/worker/run.sh
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    links:
      - rabbit
    depends_on:
      - db
      - rabbit
    volumes:
      - ~/.ethereum/rinkeby/geth.ipc:/root/.ethereum/rinkeby/geth.ipc

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
