apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-tradingdb
  labels:
    app: rabbitmq-tradingdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-tradingdb
  template:
    metadata:
      labels:
        app: rabbitmq-tradingdb
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6
        ports:
          - containerPort: 5672
          - containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "tradingdb"
          - name: RABBITMQ_DEFAULT_PASS
            value: "tradingdb"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
