apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-tradingdb
  labels:
    app: rabbitmq-tradingdb
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: "rpc"
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: "api"
  selector:
    app: rabbitmq-tradingdb
