apiVersion: v1
kind: Service
metadata:
  name: tradingdb-web
  labels:
    app: tradingdb-web
spec:
  type: "ClusterIP"
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: tradingdb-web
